# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38d22837647ef6f21396ffd585dffbd0f5924d5aa2554dbbf408e5f27844ea0c34857499c872f17907861809aad3f40de4252a594335eb3ff8d44087b6643a00

test:
  secret_key_base: 5edc4db26397d24716e441db3c6e2be72d18b5299f96f4afe96d49a2e7456897797eda1611602f28f37421b2252ed56b06d15e854ae1fe2d2d2601a9a4f0b346

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
